// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Missing Supabase environment variables');
}

// Create optimized Supabase client with performance settings
export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    // Faster auth state detection
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    // Reduce auth check frequency
    flowType: 'pkce',
  },
  global: {
    // Optimize headers for better performance
    headers: {
      'X-Client-Info': 'academic-spark-2',
    },
  },
  db: {
    // Optimize database queries
    schema: 'public',
  },
  realtime: {
    // Optimize realtime connections
    params: {
      eventsPerSecond: 10,
    },
  },
});

// Export the enhanced client
export default supabase;